export const menuData = {
  shawarma: [
    { 
      id: 1, 
      emoji: '🌯', 
      name: 'Chicken Shawarma', 
      desc: 'Classic grilled chicken roll', 
      price: '₹100',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Grilled Chicken', 'Garlic Toum', 'Pickled Cucumber', 'French Fries', 'Arabic Pita'],
      protein: '24g',
      calories: '380 kcal',
      carbs: '32g',
      isBestseller: true
    },
    { 
      id: 2, 
      emoji: '🌯', 
      name: 'Tandoori Chicken Shawarma', 
      desc: 'Smoky tandoori masala marinade', 
      price: '₹120',
      img: 'https://images.unsplash.com/photo-1626700051175-6518c4793f4f?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Tandoori Chicken', 'Mint Chutney', 'Onion Rings', 'Spicy Toum', 'Rumali Roti'],
      protein: '26g',
      calories: '410 kcal',
      carbs: '30g',
      isBestseller: true,
      spicy: true
    },
    { 
      id: 3, 
      emoji: '🌯', 
      name: 'Peri Peri Chicken Shawarma', 
      desc: 'Tossed in hot peri peri spices', 
      price: '₹120',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Peri Peri Chicken', 'Toum', 'French fries', 'Pickled turnip', 'Spicy mayo'],
      protein: '25g',
      calories: '390 kcal',
      carbs: '31g',
      spicy: true
    },
    { 
      id: 4, 
      emoji: '🌯', 
      name: 'Schezwan Chicken Shawarma', 
      desc: 'Fiery Schezwan sauce loaded roll', 
      price: '₹120',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Schezwan Chicken', 'Garlic paste', 'Onions', 'Capsicum', 'Spiced Toum'],
      protein: '24g',
      calories: '400 kcal',
      carbs: '33g',
      spicy: true
    },
    { 
      id: 5, 
      emoji: '🧀', 
      name: 'Cheese Chicken Shawarma', 
      desc: 'Extra melted cheddar & mozzarella', 
      price: '₹120',
      img: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Grilled Chicken', 'Melted Mozzarella', 'Cheddar Sauce', 'Garlic Toum', 'Arabic Pita'],
      protein: '28g',
      calories: '490 kcal',
      carbs: '35g',
      isBestseller: true
    },
    { 
      id: 6, 
      emoji: '🌯', 
      name: 'Chipotle Cheese Shawarma', 
      desc: 'Creamy chipotle sauce & melted cheese', 
      price: '₹120',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Grilled Chicken', 'Chipotle Dressing', 'Cheese Blend', 'Lettuce', 'Pita'],
      protein: '26g',
      calories: '470 kcal',
      carbs: '34g'
    },
    { 
      id: 7, 
      emoji: '🌯', 
      name: 'BBQ Chicken Shawarma', 
      desc: 'Sweet & smoky BBQ glaze chicken', 
      price: '₹120',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['BBQ chicken', 'Onions', 'Toum', 'French fries', 'Pita'],
      protein: '25g',
      calories: '420 kcal',
      carbs: '36g'
    },
    { 
      id: 8, 
      emoji: '🌯', 
      name: 'Afgani Chicken Shawarma', 
      desc: 'Mild creamy malai marinade', 
      price: '₹140',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Malai Chicken', 'Cream Toum', 'Cashew Paste', 'Spices', 'Rumali Roti'],
      protein: '27g',
      calories: '430 kcal',
      carbs: '29g'
    },
    { 
      id: 9, 
      emoji: '🌯', 
      name: 'Mexican Chicken Shawarma', 
      desc: 'Jalapeños, salsa, and hot spices', 
      price: '₹140',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Spicy Chicken', 'Jalapeños', 'Mexican Salsa', 'Toum', 'French Fries'],
      protein: '25g',
      calories: '395 kcal',
      carbs: '31g',
      spicy: true
    },
    { 
      id: 10, 
      emoji: '🔥', 
      name: 'Angaar Spl. Shawarma', 
      desc: 'Signature loaded fiery roll', 
      price: '₹140',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Double Grilled Chicken', 'Angaar Hot Sauce', 'Jalapenos', 'Pickled Turnip', 'Spiced Toum'],
      protein: '32g',
      calories: '450 kcal',
      carbs: '28g',
      isBestseller: true,
      spicy: true
    },
    { 
      id: 11, 
      emoji: '🌯', 
      name: 'Chicken Overload Shawarma', 
      desc: 'Double meat, zero veggies', 
      price: '₹140',
      img: 'https://images.unsplash.com/photo-1561651823-34fed0225408?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Loaded Grilled Chicken', 'Cashew Paste', 'Double Toum', 'Rumali Roti'],
      protein: '38g',
      calories: '520 kcal',
      carbs: '15g'
    },
  ],
  platter: [
    { 
      id: 12, 
      emoji: '🍽️', 
      name: 'Signature Chicken Platter', 
      desc: 'Classic shawarma meat with rice & hummus', 
      price: '₹250',
      img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Shredded Chicken', 'Basmati Rice', 'Hummus', 'Toum', '2 Pita Breads'],
      protein: '38g',
      calories: '650 kcal',
      carbs: '68g',
      isBestseller: true
    },
    { 
      id: 13, 
      emoji: '🍽️', 
      name: 'Peri Peri Chicken Platter', 
      desc: 'Spicy chicken, peri peri fries & toum', 
      price: '₹250',
      img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Peri Peri Chicken', 'Spicy Rice', 'Hummus', 'Peri Peri Fries', '2 Pita Breads'],
      protein: '39g',
      calories: '660 kcal',
      carbs: '70g',
      spicy: true
    },
    { 
      id: 14, 
      emoji: '🍽️', 
      name: 'BBQ Chicken Platter', 
      desc: 'BBQ chicken, fries, salad & dips', 
      price: '₹250',
      img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
      ingredients: ['BBQ chicken', 'Basmati Rice', 'BBQ dip', 'Onion Salad', '2 Pita Breads'],
      protein: '37g',
      calories: '690 kcal',
      carbs: '74g'
    },
    { 
      id: 15, 
      emoji: '🍽️', 
      name: 'Chipotle Cheese Platter', 
      desc: 'Chicken with chipotle sauce & melted cheese', 
      price: '₹250',
      img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Grilled Chicken', 'Chipotle Sauce', 'Melted Cheese', 'Rice', '2 Pita Breads'],
      protein: '42g',
      calories: '780 kcal',
      carbs: '72g'
    },
    { 
      id: 16, 
      emoji: '🍽️', 
      name: 'Schezwan Chicken Platter', 
      desc: 'Fiery chicken strips with Schezwan dip & rice', 
      price: '₹250',
      img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Schezwan Chicken', 'Spicy Rice', 'Hummus', 'Schezwan Toum', '2 Pita Breads'],
      protein: '38g',
      calories: '670 kcal',
      carbs: '71g',
      spicy: true
    },
    { 
      id: 17, 
      emoji: '🍽️', 
      name: 'Tandoori Chicken Platter', 
      desc: 'Tandoori-style chicken with mint chutney & rice', 
      price: '₹250',
      img: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Tandoori Chicken', 'Jeera Rice', 'Mint Chutney', 'Lachha Onion', '2 Pita Breads'],
      protein: '39g',
      calories: '640 kcal',
      carbs: '66g'
    },
  ],
  salad: [
    { 
      id: 18, 
      emoji: '🥗', 
      name: 'Roasted Chicken Salad', 
      desc: 'Flame roasted chicken strips over fresh greens', 
      price: '₹150',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Roasted Chicken', 'Lettuce', 'Cucumber', 'Cherry Tomatoes', 'Olive Oil Dressing'],
      protein: '22g',
      calories: '280 kcal',
      carbs: '12g'
    },
    { 
      id: 19, 
      emoji: '🥗', 
      name: 'Tandoori Chicken Salad', 
      desc: 'Tandoori chicken cubes with tangy dressing & onions', 
      price: '₹160',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Tandoori Chicken', 'Onions', 'Capsicum', 'Greens', 'Mint-Lime Vinaigrette'],
      protein: '24g',
      calories: '290 kcal',
      carbs: '11g'
    },
    { 
      id: 20, 
      emoji: '🥗', 
      name: 'Peri Peri Chicken Salad', 
      desc: 'Spicy chicken, peri peri dust, and fresh crisp greens', 
      price: '₹160',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Peri Peri Chicken', 'Bell Peppers', 'Cabbage', 'Lettuce', 'Spicy Vinaigrette'],
      protein: '23g',
      calories: '285 kcal',
      carbs: '13g',
      spicy: true
    },
    { 
      id: 21, 
      emoji: '🥗', 
      name: 'BBQ Chicken Salad', 
      desc: 'Smoky BBQ glazed chicken over loaded ranch greens', 
      price: '₹160',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['BBQ chicken', 'Corn', 'Black Beans', 'Greens', 'Light Ranch Dressing'],
      protein: '22g',
      calories: '320 kcal',
      carbs: '18g'
    },
    { 
      id: 22, 
      emoji: '🥗', 
      name: 'Chipotle Cheese Chicken Salad', 
      desc: 'Creamy chipotle chicken, greens, and cheese shreds', 
      price: '₹160',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Chipotle Chicken', 'Cheese Shreds', 'Lettuce', 'Cilantro-Lime Dressing'],
      protein: '25g',
      calories: '390 kcal',
      carbs: '15g'
    },
    { 
      id: 23, 
      emoji: '🥗', 
      name: 'High Protein Salad', 
      desc: 'Double meat, chickpeas, egg whites & greens', 
      price: '₹170',
      img: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Double Chicken', 'Chickpeas', 'Egg Whites', 'Spinach', 'Hummus Dressing'],
      protein: '36g',
      calories: '420 kcal',
      carbs: '19g',
      isBestseller: true
    },
  ],
  mocktail: [
    { 
      id: 24, 
      emoji: '🥤', 
      name: 'Mint Mojito', 
      desc: 'Fresh mint, lime wedges, simple syrup & soda', 
      price: '₹60',
      img: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Fresh Mint Leaves', 'Lime Wedges', 'Simple Syrup', 'Sparkling Soda', 'Crushed Ice'],
      protein: '0g',
      calories: '85 kcal',
      carbs: '22g',
      isBestseller: true
    },
    { 
      id: 25, 
      emoji: '🍹', 
      name: 'Blue Lagoon Mojito', 
      desc: 'Blue curacao, lemon juice & club soda', 
      price: '₹80',
      img: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Blue Curacao Syrup', 'Lemon Juice', 'Sprite/Soda', 'Lemon Slices', 'Mint'],
      protein: '0g',
      calories: '90 kcal',
      carbs: '23g'
    },
    { 
      id: 26, 
      emoji: '🍉', 
      name: 'Watermelon Mojito', 
      desc: 'Fresh watermelon pulp, mint & soda', 
      price: '₹80',
      img: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
      ingredients: ['Watermelon Juice', 'Fresh Mint', 'Lime Juice', 'Soda', 'Ice'],
      protein: '0g',
      calories: '95 kcal',
      carbs: '24g'
    },
  ]
};
